- name: Configure EC2 instance
  remote_user: ec2-user
  become: yes
  become_method: sudo
  hosts: all

  tasks:
    vars:
      packages:
        - httpd
        - nginx
        - docker

    - name: install softwares
      yum:
        name: {{items}}
        state: installed
      loop: {{packages}}
