version: "3"

services:
  web1:
    image: durgaprasaduniq/prasad:v2
    container_name: NTR
    ports:
      - "8091:8080"

  web2:
    image: nginx
    container_name: DEVARA
    ports:
       - "8083:80"
