version: "3"

services:
  web1:
    image: durgaprasaduniq/prasad:v2
    container_name: NTR-1
    ports:
      - "8091:8080"

  web2:
    image: nginx
    container_name: DEVARA-1
    ports:
       - "8083:80"

  web3:
    image: tomcat
    container_name: devara-2
    ports:
       - "8084:8080
